### ISSUE TITLE
If the song is a remix the app fetch the original one

### ISSUE THREAD

**Issue by josico14** [goktug97/yet-another-spotify-lyrics#11]
Hi goktug97, first of all, I've been using your app lately and is awesome.
I noticed that when the song is a remix (for example https://open.spotify.com/track/5YYW3yRktprLRr47WK219Y?si=hkJTpRAIQT-OfVarzAdFug) the app display the lyrics of the original song.
I took a look to your code and saw that in the **fetch_lyrics** function inside **utils.py** you used a regex that removes all character placed after a "-". I suppose that you did that for something (don't know what) but it makes the app take the wrong lyrics for that type of songs.

**Comment by goktug97** [comment]
Hi, instead of removing after the dash, it now removes only the dash https://github.com/goktug97/yet-another-spotify-lyrics/commit/e90468aa5cac8524ea96c09e5331ce31d6c52a14.

As far as I remember, the string after the dash for a music was causing me a problem so I removed it completly but I can't remember which one, that is probably why I did that.

**Comment by josico14** [comment]
It works perfectly now! Thanks a lot!
Sometimes the lyrics aren't the correct ones but not a problem of your app, just google using the wrong lyrics. Maybe using Genius would be an option? If you want I can try implement Genius search if you don't mind.

**Comment by goktug97** [comment]
I think scraping Genius can be a problem because they have an API and scraping directly is probably forbidden on their side. Unfortunately, I don't want to use an API because it requires generation of a private key and I don't want to force users to create an API key.
