### ISSUE TITLE
Album cover not working at all?

### ISSUE THREAD

**Issue by DasVoelkel** [goktug97/yet-another-spotify-lyrics#6]
Album covers aren't loading for me at all.
Is there some dependency i may be missing that is not included in your list?
Running a blank arch with minimal setup on it.

Also, where are you pulling the lyrics data from? Many german songs aren't working and i wanted to check if that was just a database problem.
Edit:
Nevermind, opening utils.py kinda answers that question.

**Comment by goktug97** [comment]
Can you access https://www.spotify.com, if you can, I think it might be a problem with the terminal emulator. Can you try https://st.suckless.org/ to see if the problem is the terminal emulator.

I am parsing the google page of the lyrics. For example <song name> lyrics. You can try it in Google with a german song to see if it appears, if it does it might be a parsing problem, let me know.

**Comment by DasVoelkel** [comment]
works fine with suckless, i was using alucritty.
